language: ruby
cache: bundler
sudo: false
before_script:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
  - mysql -e 'create database ranked_model_test;'
  - psql -c 'create database ranked_model_test;' -U postgres
rvm:
  - 2.4.4
  - 2.5.1
  - jruby-9.1.17.0
  - rbx-3.107
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
services:
  - mysql
  - postgresql
gemfile:
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile
matrix:
  exclude:
    - rvm: jruby-9.1.17.0
      gemfile: gemfiles/rails_5_2.gemfile
    - rvm: rbx-3.107
      gemfile: gemfiles/rails_5_2.gemfile
    - rvm: 2.4.4
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: rbx-3.107
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: jruby-9.1.17.0
      gemfile: gemfiles/rails_6_0.gemfile
